project:
  title: "Website"
  output-dir: docs
  type: website
  #output-dir: docs
  #execute-dir: project
  resources: 
    - "CNAME"
    - "figs/"
  #  - "www/cv/"
  #  - "www/images"

website:
  title: "Alessandro Conigli"
  site-url: "https://bunniies.github.io"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  favicon: /figs/favicon.ico
  navbar:
    logo: /figs/icon.ico
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: contents/about_me/index.qmd
      - text: "Blog"
        menu:
          - text: "test 1"
            icon: /figs/icon.ico
            file: about.qmd
          - text: "test 2"
            file: about.qmd
      - text: "Publications"
        file: contents/publications/index.qmd

  twitter-card: true
        
  page-footer: 
    background: light
    left: '© 2023, Alessandro Conigli'
    right: 
      - icon: house
        href: https://bunniies.github.io
      - icon: github
        href: https://github.com/Bunniies
      - icon: linkedin
        href: https://www.linkedin.com/in/alessandro-conigli-81078a195/
        